# Generated by Django 5.2.6 on 2025-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Template category (Hero, About, Portfolio, Services, etc.)', max_length=50)),
                ('name', models.CharField(help_text='Unique template identifier name', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name for the template', max_length=150)),
                ('description', models.TextField(help_text='Brief description of the template functionality')),
                ('file_path_template', models.CharField(help_text='File path template location', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portfolio Template',
                'verbose_name_plural': 'Portfolio Templates',
                'db_table': 'portfolio_templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='portfolio_t_categor_48ed6e_idx'), models.Index(fields=['name'], name='portfolio_t_name_947078_idx'), models.Index(fields=['is_active'], name='portfolio_t_is_acti_e91369_idx')],
            },
        ),
    ]
