manager_task:
  description: >
    **OVERALL PROJECT COORDINATION:**
    - Receive and analyze the user’s request in full detail.
    - Break down the requirements into specific tasks for different teams and tools.
    - Assign tasks to the UI/UX Team Leader to create a list of required components.
    - Ensure that all components needed for the page are accounted for.
    - If some components are missing, delegate creation of new components to appropriate tools.
    - Route tasks to Combiner and Aggregator agents for integration, validation, and analytics.
    - Track the progress of all tasks and ensure proper sequencing and coordination across teams.
    - Maintain smooth communication and ensure deliverables meet the requirements.
    Context: {user_prompt}
  expected_output: >
    - A detailed plan outlining tasks, dependencies, and timelines.
    - Assignment of tasks to UI/UX Team Leader and other specialist agents.
    - Verification process to ensure components are complete or need creation.
    - Clear next steps and priority areas for implementation.
  agent: manager_agent


uiux_team_leader_task:
  description: >
    **UI/UX PLANNING & COMPONENT DESIGN:*
    - Based on the requirements provided by the Manager, create a structured list of all components needed for the page.
    - Focus on designing essential components such as:
      - Header/Navigation
      - Hero Section
      - About/Introduction Section
      - Features/Services Section
      - Skills/Expertise Section
      - Testimonials/Reviews Section
      - Contact Section
      - Footer
    - Check with the database using the get_existing_components tool to see if these components are already available.
    - If get_existing_components tool returns empty list, request the creation of new components using the Create New Component tool.
    - If any required component is missing, request the creation of new components using the Create New Component tool.
    - Ensure the final list of components supports a seamless and responsive user experience.

  expected_output: >
    - Complete list of required components.
    - Identification of existing and missing components.
    - Recommendations for creating new components where necessary.
    - UI/UX design plan ensuring cohesive and interactive user experience.
  agent: uiux_team_leader_agent


combiner_task:
  description: >
    **COMPONENT ASSEMBLY & SYSTEM INTEGRATION:**
    - Combine available components to build the full page layout.
    - Integrate new components created by other tools with existing ones.
    - Ensure smooth interaction between all components and sections.
    - Assemble HTML and CSS files based on the approved component list.
    - Coordinate with backend services if necessary to link UI with APIs or authentication flows.
    - Ensure navigation, layout, and transitions work seamlessly across devices.
    - Validate that all elements are correctly linked and perform as expected.

  expected_output: >
    - Complete, integrated page layout with all components assembled.
    - HTML and CSS files ready for deployment.
    - Functional navigation and interactive elements working as designed.
    - Integration documentation showing how components and backend systems connect.
  agent: combiner_agent

aggregator_task:
  description: >
    **FINAL REVIEW, TESTING & APPROVAL:**
    - Review the integrated page created by the Combiner.
    - Check for consistency, responsiveness, and usability across devices.
    - Test navigation, functionality, and performance to ensure everything works as expected.
    - Identify any issues, missing links, or layout problems.
    - Approve the final page if it meets quality standards or request adjustments.
    - Provide feedback and documentation to ensure the page is ready for deployment.

  expected_output: >
    - Final validation report covering functionality, responsiveness, and design consistency.
    - Approved HTML page ready for deployment.
    - Documentation highlighting issues and resolutions.
    - Recommendations for further improvements if needed.
  agent: aggregator_agent

